#!/bin/sh
#
# port knocking script
# - stolen from Arch wiki
#
# usage: knock 127.0.0.1 8888 7777 9999
#

HOST=$1; shift
for ARG in "$@"; do
	nmap -Pn --host_timeout 100 --max-retries 0 -p $ARG $HOST
done
